### ISSUE TITLE
Dataset download error

### ISSUE THREAD

**Issue by caibucai22** [mila-iqia/cableinspect-ad-code#18]
This is excellent work, but when I tried to follow it, I found that the dataset download link provided was invalid. Could you please provide a valid download link? 

Thanks again for your contribution to the community.

**Comment by sthoduka** [comment]
It redirects to this page: https://acces-restreint.solutions.hydroquebec.com/ which says "Hydro-Québec website unavailable from abroad".

Is it possible to upload the dataset elsewhere? Thanks!

**Comment by akshathaarodi** [comment]
We have updated the dataset link on our [project website](https://mila-iqia.github.io/cableinspect-ad/).

**Comment by sthoduka** [comment]
thanks a lot! I was able to download it.

**Comment by akshathaarodi** [comment]
The dataset link is updated now.

**Comment by willyawan16** [comment]
Cannot download the dataset again, could you please provide the working link? Thanks

**Comment by akshathamila** [comment]
If you cannot access data, please contact us over email and we will share an alternate link.
